name: flutter_esc_pos_blue
description: Flutter esc pos blueooth plugin
version: 0.0.2
homepage: https://github.com/10urbulut/flutter_esc_pos_blue

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_blue_plus: ^1.3.1
  rxdart: ^0.27.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

 